# electron_spread.py

import numpy as np
import pandas as pd
from scipy.stats import nbinom
from tqdm import tqdm

def electron_conversion(dE_MeV, fano_factor=2.71, w_eV=2.509):
    """
    Convert deposited energy [MeV] to the number of electrons via the negative binomial distribution.
    Args:
        dE_MeV (float): Energy loss in MeV.
        fano_factor (float): Effective Fano factor (dimensionless).
        w_eV (float): Mean energy to create an electron (eV).
    Returns:
        int: Number of electrons generated by dE_MeV energy loss.
    """
    if dE_MeV <= 0:
        return 0
    dE_eV = dE_MeV * 1e6 # changes MeV to eV to match w
    mu_nb = dE_eV / w_eV
    p = 1.0 / fano_factor
    if not (0 < p < 1):
        return 0
    r = mu_nb * (p / (1.0 - p))
    if r <= 0:
        return 0
    return nbinom(r, p).rvs()

def kernel_size_from_sigma(
    sigma_um,
    grid_spacing_um,
    N_sigma=6
):
    """
    Calculate the kernel size (in grid points) to cover ±N_sigma*sigma_um.
    Args:
        sigma_um (float): Standard deviation of the Gaussian [microns].
        grid_spacing_um (float): Grid step size [microns].
        N_sigma (int): Number of sigmas to include in kernel (default: 6).
    Returns:
        int: Odd integer kernel size (number of grid points).
    """
    size = int(np.ceil(2 * N_sigma * sigma_um / grid_spacing_um)) + 1
    if size % 2 == 0:
        size += 1
    return size

def min_region_size_um_for_kernel(
    sigma_um,
    grid_spacing_um,
    min_region_um=50,
    N_sigma=6 # if σ = 3.14 μm and N_sigma = 6, kernel covers ±18.84 μm from the center, or about 37.68 μm
):
    """
    Ensure region is large enough (in microns) for a given sigma and grid.
    Args:
        sigma_um (float): Standard deviation of Gaussian [microns].
        grid_spacing_um (float): Hi-res grid step size [microns].
        min_region_um (float): Minimum region size allowed [microns].
        N_sigma (int): How many sigmas to cover in the kernel.
    Returns:
        float: The larger of min_region_um or the kernel's required region [microns].
    """
    kernel_size = kernel_size_from_sigma(sigma_um, grid_spacing_um, N_sigma)
    region_um = kernel_size * grid_spacing_um
    return max(min_region_um, region_um)

def gaussian_sum_kernel(
    size,                   # int, number of grid points (should be odd)
    sigma_um,               # float, sigma of the main Gaussian [microns]
    grid_spacing_um=1.0,    # float, grid step size [microns]
    w_list=[0.17519, 0.53146, 0.29335],
    c_list=[0.4522, 0.8050, 1.4329]
):
    """
    Generate a kernel on a physical grid (micron-based) using a sum of 3 Gaussians.
    Args:
        size (int): Kernel grid size (should be odd).
        sigma_um (float): Main sigma [microns].
        grid_spacing_um (float): Grid step size [microns].
        w_list (list): Weights for the sum-of-Gaussians.
        c_list (list): Multiplicative factors for each Gaussian's width.
    Returns:
        np.ndarray: [size x size] normalized kernel, grid units in microns.
    """
    ax = (np.arange(size) - size // 2) * grid_spacing_um   # [microns]
    xx, yy = np.meshgrid(ax, ax)
    rr2 = xx ** 2 + yy ** 2  # [micron^2]
    kernel = np.zeros_like(xx, dtype=float)
    for w, c in zip(w_list, c_list):
        s = sigma_um * c
        norm = 2 * np.pi * (s ** 2)
        kernel += w * np.exp(-rr2 / (2 * s ** 2)) / norm
    kernel = np.maximum(kernel, 0)
    kernel /= kernel.sum() if kernel.sum() > 0 else 1
    return kernel

def spread_electrons_to_patch(
    array,
    x_idx,
    y_idx,
    n_electrons,
    kernel
):
    """
    Spread electrons into an array patch using a multinomial distribution.
    Args:
        array (np.ndarray): 2D array where electrons are to be spread.
        x_idx, y_idx (int): Central index in array for electron source.
        n_electrons (int): Number of electrons to distribute.
        kernel (np.ndarray): Kernel for charge diffusion, shape must match patch.
    Modifies:
        array (np.ndarray): Electrons are added to this array in-place.
    """
    size = kernel.shape[0]
    offset = size // 2

    # Calculate patch placement bounds in array (hi-res)
    x0, x1 = x_idx - offset, x_idx + offset + 1
    y0, y1 = y_idx - offset, y_idx + offset + 1

    # Calculate the region to actually insert (handle array edges)
    patch_x0, patch_y0 = max(0, x0), max(0, y0)
    patch_x1, patch_y1 = min(array.shape[1], x1), min(array.shape[0], y1)

    # Region in kernel to use (handle kernel cropping)
    kx0 = patch_x0 - x0
    ky0 = patch_y0 - y0
    kx1 = kx0 + (patch_x1 - patch_x0)
    ky1 = ky0 + (patch_y1 - patch_y0)

    patch_kernel = kernel[ky0:ky1, kx0:kx1]
    patch_kernel = np.maximum(patch_kernel, 0)
    patch_kernel /= patch_kernel.sum() if patch_kernel.sum() > 0 else 1

    draws = np.random.default_rng().multinomial(n_electrons, patch_kernel.ravel())
    for count, (dy, dx) in zip(draws, np.argwhere(np.ones_like(patch_kernel))):
        if count > 0:
            i = patch_y0 + dy
            j = patch_x0 + dx
            array[i, j] += count

def process_electrons_to_DN(
    csvfile,
    gain_txt,
    n_pixels=4096,                  # number of detector pixels on a side
    pixel_size_micron=10.0,         # low-res detector pixel size [microns]
    hi_res_grid_spacing_micron=1.0, # hi-res grid spacing [microns]
    chunksize=200_000,
    sigma_micron=3.14,         # charge diffusion sigma [microns]
    N_sigma=6,
    output_DN_path=None
):
    """
    Convert a list of simulated charge deposition events (CSV) to a detector-scale
    map in digital numbers (DN), including charge diffusion and gain correction.

    Parameters
    ----------
    csvfile : str or Path
        Path to CSV file with charge deposition events. Must include columns:
        'x' (float, microns), 'y' (float, microns), 'dE' (float, MeV).
    gain_txt : str or Path
        Path to the detector gain map text file. Must contain at least 6 columns per row;
        column 5 (zero-based) gives the gain (e⁻/DN) for each 32x32 supercell.
    n_pixels : int, optional
        Number of detector pixels along one axis (detector assumed square).
        Default is 4096.
    pixel_size_micron : float, optional
        Physical size of a detector pixel, in microns (μm). Default is 10.0 μm.
    hi_res_grid_spacing_micron : float, optional
        Step size for the high-resolution grid (charge diffusion, microns). Default is 1.0 μm.
    chunksize : int, optional
        Number of rows per chunk when reading the CSV (for memory efficiency).
        Default is 200,000.
    sigma_micron : float, optional
        Standard deviation of the charge diffusion kernel, in microns. Default is 3.14 μm.
    N_sigma : int, optional
        The kernel size extends ±N_sigma * sigma in each direction.
        Default is 6.
    output_DN_path : str or Path, optional
        If provided, the DN map will be saved to this path as a .npy file.

    Returns
    -------
    H_detector_DN : np.ndarray (float)
        2D array of shape (n_pixels, n_pixels), units of digital numbers (DN).

    Raises
    ------
    AssertionError
        If detector size or pixel size is not divisible by the high-res grid spacing.
        If the gain map shape does not match the output array.
    """
    # Determine size of hi-res grid
    det_size_micron = n_pixels * pixel_size_micron
    n_hi = int(det_size_micron / hi_res_grid_spacing_micron)
    assert np.isclose(n_hi * hi_res_grid_spacing_micron, det_size_micron, atol=1e-5), \
        "Detector size must be divisible by hi-res grid spacing."

    # Prepare kernel for diffusion (on hi-res grid, in microns)
    kernel_size_hi = kernel_size_from_sigma(
        sigma_micron, hi_res_grid_spacing_micron, N_sigma
    )
    kernel = gaussian_sum_kernel(
        size=kernel_size_hi,
        sigma_um=sigma_micron,
        grid_spacing_um=hi_res_grid_spacing_micron
    )
    H_hi = np.zeros((n_hi, n_hi), dtype=float)

    # Process energy deposition events
    for chunk in pd.read_csv(csvfile, sep=',', chunksize=chunksize):
        xs_um = chunk['x'].to_numpy()
        ys_um = chunk['y'].to_numpy()
        dEs_MeV = chunk['dE'].to_numpy()
        for x_um, y_um, dE in tqdm(zip(xs_um, ys_um, dEs_MeV), desc="Processing events"):
            n_electrons = electron_conversion(dE)
            if n_electrons > 0:
                # Convert physical position to hi-res grid index
                x_hi_idx = int(np.floor(x_um / hi_res_grid_spacing_micron))
                y_hi_idx = int(np.floor(y_um / hi_res_grid_spacing_micron))
                half_patch = kernel_size_hi // 2

                patch = np.zeros((kernel_size_hi, kernel_size_hi), dtype=float)
                spread_electrons_to_patch(
                    patch, half_patch, half_patch, n_electrons, kernel
                )

                # Insert patch into H_hi, handle edges
                y0 = y_hi_idx - half_patch
                y1 = y0 + kernel_size_hi
                x0 = x_hi_idx - half_patch
                x1 = x0 + kernel_size_hi

                py0 = max(0, -y0)
                py1 = kernel_size_hi - max(0, y1 - n_hi)
                px0 = max(0, -x0)
                px1 = kernel_size_hi - max(0, x1 - n_hi)
                hy0 = max(0, y0)
                hy1 = min(n_hi, y1)
                hx0 = max(0, x0)
                hx1 = min(n_hi, x1)
                H_hi[hy0:hy1, hx0:hx1] += patch[py0:py1, px0:px1]

    # Downsample hi-res grid into detector pixel grid by binning
    downsample_factor = int(pixel_size_micron / hi_res_grid_spacing_micron)
    assert np.isclose(downsample_factor * hi_res_grid_spacing_micron, pixel_size_micron, atol=1e-5), \
        "Detector pixel size must be divisible by hi-res grid spacing."
    H_detector = H_hi.reshape(
        n_pixels, downsample_factor,
        n_pixels, downsample_factor
    ).sum(axis=(1, 3))

    # Apply gain correction (electrons to DNs)
    gain_array = np.loadtxt(gain_txt)[:, 5].reshape((32, 32))
    supercell_size = n_pixels // 32
    gain_map = np.kron(gain_array, np.ones((supercell_size, supercell_size)))
    assert gain_map.shape == H_detector.shape
    gain_map_safe = np.where(gain_map > 0, gain_map, np.nan)
    H_detector_DN = H_detector / gain_map_safe

    if output_DN_path:
        np.save(output_DN_path, H_detector_DN)
        print(f"Saved DN array to {output_DN_path}")

    return H_detector_DN

def process_pid_electrons_zoom(
    csvfile,
    pid,
    delta_pids,
    sigma_micron=3.14,
    hi_res_grid_spacing_micron=1.0,
    N_sigma=6
):
    """
    Generate a high-resolution 2D patch representing the spatial distribution of charge
    deposited by a primary event (PID) and its delta rays, convolved with a Gaussian
    charge diffusion kernel. 

    Parameters
    ----------
    csvfile : str or Path
        Path to a CSV file containing event data. The file must include columns:
        'PID' (int), 'x' (float, microns), 'y' (float, microns), and 'dE' (float, MeV).
    pid : int
        The parent event PID whose primary electrons are to be included.
    delta_pids : iterable of int
        Iterable of delta-ray PIDs (children) to include in addition to the parent PID.
    sigma_micron : float, optional
        St dev of the Gaussian charge diffusion kernel, in microns (μm).
        Default is 3.14 μm.
    hi_res_grid_spacing_micron : float, optional
        Spatial resolution of the output patch, i.e., the size of each pixel in microns.
        Default is 1.0 μm.
    N_sigma : int, optional
        Number of standard deviations to expand the bounding box for including the
        Gaussian kernel tails. Default is 6.

    Returns
    -------
    patch : np.ndarray (float)
        2D array of shape (n_pix_y, n_pix_x), representing the spatially distributed
        charge in arbitrary units (usually number of electrons per pixel) after
        convolution with the diffusion kernel.
    x_coords_um : np.ndarray (float)
        1D array of length n_pix_x. X coordinates (in microns) of the pixel centers along the
        patch's horizontal axis (columns).
    y_coords_um : np.ndarray (float)
        1D array of length n_pix_y. Y coordinates (in microns) of the pixel centers along the
        patch's vertical axis (rows).

    Raises
    ------
    ValueError
        If no events matching the specified PID or delta_pids are found in the CSV file.
    """
    # Read in all events for the parent and associated deltas
    wanted_pids = set([pid] + list(delta_pids))
    df = pd.read_csv(csvfile)
    mask = df['PID'].isin(wanted_pids)
    if not mask.any():
        raise ValueError("No events found for this PID + deltas in the CSV.")

    # Find bounding box (in microns) of ALL these events
    xs = df.loc[mask, 'x']
    ys = df.loc[mask, 'y']
    x_min, x_max = xs.min(), xs.max()
    y_min, y_max = ys.min(), ys.max()

    # Expand bounds by kernel tail (N_sigma * sigma)
    expand = N_sigma * sigma_micron
    x0_um = x_min - expand
    x1_um = x_max + expand
    y0_um = y_min - expand
    y1_um = y_max + expand

    # Determine patch size in hi-res grid points
    n_pix_x = int(np.ceil((x1_um - x0_um) / hi_res_grid_spacing_micron))
    n_pix_y = int(np.ceil((y1_um - y0_um) / hi_res_grid_spacing_micron))

    # Allocate the patch
    patch = np.zeros((n_pix_y, n_pix_x), dtype=float)

    # Prepare diffusion kernel
    kernel_size_hi = kernel_size_from_sigma(sigma_micron, hi_res_grid_spacing_micron, N_sigma)
    kernel = gaussian_sum_kernel(
        size=kernel_size_hi,
        sigma_um=sigma_micron,
        grid_spacing_um=hi_res_grid_spacing_micron
    )

    # Spread all electrons from all events into the patch
    dEs = df.loc[mask, 'dE']
    for x_um, y_um, dE in zip(xs, ys, dEs):
        n_electrons = electron_conversion(dE)
        if n_electrons > 0:
            x_idx = int(np.floor((x_um - x0_um) / hi_res_grid_spacing_micron))
            y_idx = int(np.floor((y_um - y0_um) / hi_res_grid_spacing_micron))
            spread_electrons_to_patch(patch, x_idx, y_idx, n_electrons, kernel)

    # return patch and coordinate system for overlay/labeling
    x_coords_um = x0_um + np.arange(n_pix_x) * hi_res_grid_spacing_micron
    y_coords_um = y0_um + np.arange(n_pix_y) * hi_res_grid_spacing_micron

    return patch, x_coords_um, y_coords_um

def process_electrons_to_DN_by_blob(
    csvfile,
    gain_txt,
    n_pixels=4096,
    pixel_size_micron=10.0,
    hi_res_grid_spacing_micron=1.0,
    sigma_micron=3.14,
    N_sigma=6,
    output_DN_path=None
):
    # Prepare hi-res detector array
    det_size_micron = n_pixels * pixel_size_micron
    n_hi = int(det_size_micron / hi_res_grid_spacing_micron)
    H_hi = np.zeros((n_hi, n_hi), dtype=float)

    # Prepare diffusion kernel (for per-event spreading)
    kernel_size_hi = kernel_size_from_sigma(sigma_micron, hi_res_grid_spacing_micron, N_sigma)
    kernel = gaussian_sum_kernel(
        size=kernel_size_hi,
        sigma_um=sigma_micron,
        grid_spacing_um=hi_res_grid_spacing_micron
    )
    half_patch = kernel_size_hi // 2

    # Read whole CSV and group by PID (requires enough RAM for this step) ---
    df = pd.read_csv(csvfile)
    if 'PID' not in df.columns:
        raise ValueError("CSV must have a 'PID' column for grouping.")

    for pid, group in tqdm(df.groupby('PID'), desc="Processing primary GCRs"):
        xs_um = group['x'].to_numpy()
        ys_um = group['y'].to_numpy()
        dEs_MeV = group['dE'].to_numpy()

        # Compute bounds (min/max) in microns for this blob ---
        x_min, x_max = xs_um.min(), xs_um.max()
        y_min, y_max = ys_um.min(), ys_um.max()
        # Expand bounds by N_sigma × sigma to fit all kernels
        expand = N_sigma * sigma_micron
        patch_x0_um = x_min - expand
        patch_x1_um = x_max + expand
        patch_y0_um = y_min - expand
        patch_y1_um = y_max + expand

        # Calculate patch size (hi-res grid points) ---
        patch_width = int(np.ceil((patch_x1_um - patch_x0_um) / hi_res_grid_spacing_micron))
        patch_height = int(np.ceil((patch_y1_um - patch_y0_um) / hi_res_grid_spacing_micron))
        # Make sure patch is at least as big as one kernel (for single-event "blobs")
        patch_width = max(patch_width, kernel_size_hi)
        patch_height = max(patch_height, kernel_size_hi)

        patch = np.zeros((patch_height, patch_width), dtype=float)

        # Process all events in this blob patch ---
        for x_um, y_um, dE in zip(xs_um, ys_um, dEs_MeV):
            n_electrons = electron_conversion(dE)
            if n_electrons > 0:
                # Convert position in microns to patch indices
                x_idx = int(np.floor((x_um - patch_x0_um) / hi_res_grid_spacing_micron))
                y_idx = int(np.floor((y_um - patch_y0_um) / hi_res_grid_spacing_micron))
                spread_electrons_to_patch(
                    patch, x_idx, y_idx, n_electrons, kernel
                )

        # Insert this patch into the main hi-res array ---
        # Calculate location in H_hi
        hi_x0 = int(np.floor(patch_x0_um / hi_res_grid_spacing_micron))
        hi_y0 = int(np.floor(patch_y0_um / hi_res_grid_spacing_micron))
        hi_x1 = hi_x0 + patch_width
        hi_y1 = hi_y0 + patch_height

        # Handle edges (clip if needed)
        px0 = max(0, -hi_x0)
        py0 = max(0, -hi_y0)
        px1 = patch_width - max(0, hi_x1 - n_hi)
        py1 = patch_height - max(0, hi_y1 - n_hi)
        hix0 = max(0, hi_x0)
        hiy0 = max(0, hi_y0)
        hix1 = min(n_hi, hi_x1)
        hiy1 = min(n_hi, hi_y1)

        H_hi[hiy0:hiy1, hix0:hix1] += patch[py0:py1, px0:px1]

    # -- Downsample and apply gain as before --
    downsample_factor = int(pixel_size_micron / hi_res_grid_spacing_micron)
    H_detector = H_hi.reshape(
        n_pixels, downsample_factor,
        n_pixels, downsample_factor
    ).sum(axis=(1, 3))

    gain_array = np.loadtxt(gain_txt)[:, 5].reshape((32, 32))
    supercell_size = n_pixels // 32
    gain_map = np.kron(gain_array, np.ones((supercell_size, supercell_size)))
    gain_map_safe = np.where(gain_map > 0, gain_map, np.nan)
    H_detector_DN = H_detector / gain_map_safe

    if output_DN_path:
        np.save(output_DN_path, H_detector_DN)
        print(f"Saved DN array to {output_DN_path}")

    return H_detector_DN  
    
# new main ---------------
if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(
        description="Spread electrons and convert to DNs from cosmic ray sim CSV (blob-patch processing)."
    )
    parser.add_argument('--csvfile', type=str, required=True, help='CSV file with energy loss events (microns, MeV)')
    parser.add_argument('--gain_txt', type=str, required=True, help='Gain map .txt file (column 5 = gain e/DN)')
    parser.add_argument('--output', type=str, default=None, help='Optional output .npy path for DN array')
    args = parser.parse_args()

    process_electrons_to_DN_by_blob(args.csvfile, args.gain_txt, output_DN_path=args.output)
